# Ender-3 S1 (STM32F401RC / Creality v2.4.S1_301F4) profile
#
# Usage:
# 1) Open Marlin/config.ini
# 2) Set:
#      ini_use_config = ender3-s1-f4.ini@ender3_s1_f4
# 3) Build with env:
#      STM32F401RC_creality

[config:ender3_s1_f4]
motherboard                              = BOARD_CREALITY_V24S1_301F4
custom_machine_name                      = "Ender-3 S1 F4"
x_bed_size                               = 220
y_bed_size                               = 220
z_max_pos                                = 270
